import crypto from 'crypto';
import { EventDao } from '@storage/daos/EventDao';
import { KTResult } from './KTAnalysis';
import { NormalizedUIREvent } from '@models/uir/UIREvent';

export interface IncidentReport {
  id: string;
  timestamp: number;
  summary: string;
  rootCause: string;
  affectedServices: string[];
  markdown: string;
  webhookPayload: object;
}

export class ReportGenerator {
  private eventDao: EventDao;

  constructor() {
    this.eventDao = new EventDao();
  }

  async generateForIncident(fingerprint: string, rootCauseReport: KTResult): Promise<IncidentReport> {
    const events = this.eventDao.findByFingerprint(fingerprint, 5);
    const summary = `Afen detected recurring ${rootCauseReport.rootCauseCandidates[0]?.nodeId ?? 'unknown'} error pattern.`;
    const markdown = this.buildMarkdown(summary, events, rootCauseReport);
    const webhookPayload = {
      event_type: 'incident',
      fingerprint,
      severity: rootCauseReport.rootCauseCandidates[0]?.confidence > 0.7 ? 'high' : 'medium',
      timestamp: Date.now(),
      details: {
        root_cause: rootCauseReport.rootCauseCandidates[0]?.nodeId,
        occurrence_count: events.length,
        first_seen: events[0]?.ingestedAt,
      },
    };
    return {
      id: crypto.randomUUID(),
      timestamp: Date.now(),
      summary,
      rootCause: rootCauseReport.rootCauseCandidates[0]?.nodeId ?? 'unknown',
      affectedServices: ['unknown'],
      markdown,
      webhookPayload,
    };
  }

  private buildMarkdown(summary: string, events: NormalizedUIREvent[], report: KTResult): string {
    let md = `# Afen Incident Report\n\n`;
    md += `## Summary\n${summary}\n\n`;
    md += `## Root Cause Candidates\n`;
    for (const cand of report.rootCauseCandidates.slice(0, 3)) {
      md += `- **${cand.nodeId}** (confidence: ${cand.confidence})\n`;
      md += `  - Evidence: ${cand.evidence.join(', ')}\n`;
    }
    md += `\n## Sample Events\n`;
    for (const ev of events.slice(0, 3)) {
      md += `- ${new Date(ev.ingestedAt).toISOString()}: ${ev.errorType} – ${ev.message.substring(0, 80)}\n`;
    }
    md += `\n*Generated by Afen Intelligence Layer*`;
    return md;
  }
}