services:
  afen-app:
    build:
      context: ..
      dockerfile: configs/Dockerfile
    image: ghcr.io/anamnadmin/afen:latest
    container_name: afen-app
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped